import json
from pathlib import Path

nodes = [
    {"id": "cadrage", "label": "Cadrage", "type": "concept", "source_file": "CLAUDE.md", "confidence": "EXTRACTED", "description": "First pipeline stage: mission parameters and scoping"},
    {"id": "ingestion", "label": "Ingestion", "type": "module", "source_file": "CLAUDE.md", "confidence": "EXTRACTED", "description": "File import stage in the audit pipeline"},
    {"id": "extraction", "label": "Extraction", "type": "module", "source_file": "CLAUDE.md", "confidence": "EXTRACTED", "description": "Data processing stage after ingestion"},
    {"id": "planification", "label": "Planification", "type": "module", "source_file": "CLAUDE.md", "confidence": "EXTRACTED", "description": "Risk mapping and threshold calculation stage"},
    {"id": "controles", "label": "Controles", "type": "module", "source_file": "CLAUDE.md", "confidence": "EXTRACTED", "description": "Deterministic audit tests stage"},
    {"id": "revue", "label": "Revue", "type": "module", "source_file": "CLAUDE.md", "confidence": "EXTRACTED", "description": "Exception review stage"},
    {"id": "generation", "label": "Generation", "type": "module", "source_file": "CLAUDE.md", "confidence": "EXTRACTED", "description": "Work file generation stage"},
    {"id": "opinion", "label": "Opinion", "type": "concept", "source_file": "CLAUDE.md", "confidence": "EXTRACTED", "description": "Final audit opinion validation stage"},
    {"id": "llm_philosophy", "label": "LLM Philosophy", "type": "concept", "source_file": "CLAUDE.md", "confidence": "EXTRACTED", "description": "Calcul=Python, Interpretation=IA, Supervision=Humain"},
    {"id": "llm_client", "label": "LLMClient", "type": "module", "source_file": "CLAUDE.md", "confidence": "EXTRACTED", "description": "Abstraction layer for LLM calls"},
    {"id": "claude_sonnet", "label": "Claude Sonnet", "type": "component", "source_file": "CLAUDE.md", "confidence": "EXTRACTED", "description": "Default model for interpretation (claude-sonnet-4-6)"},
    {"id": "claude_haiku", "label": "Claude Haiku", "type": "component", "source_file": "CLAUDE.md", "confidence": "EXTRACTED", "description": "Model for column mapping (claude-haiku-4-5)"},
    {"id": "controls_module", "label": "Controls Module", "type": "module", "source_file": "CLAUDE.md", "confidence": "EXTRACTED", "description": "Deterministic audit controls engine"},
    {"id": "storage_module", "label": "Storage Module", "type": "module", "source_file": "CLAUDE.md", "confidence": "EXTRACTED", "description": "SQLite per-project storage"},
    {"id": "planning_module", "label": "Planning Module", "type": "module", "source_file": "CLAUDE.md", "confidence": "EXTRACTED", "description": "Risk analysis and threshold calculation"},
    {"id": "statemachine_module", "label": "StateMachine Module", "type": "module", "source_file": "CLAUDE.md", "confidence": "EXTRACTED", "description": "Pipeline state transitions management"},
    {"id": "api_routes", "label": "API Routes", "type": "module", "source_file": "CLAUDE.md", "confidence": "EXTRACTED", "description": "FastAPI routes for the Python sidecar"},
    {"id": "registry_py", "label": "controls/registry.py", "type": "module", "source_file": "CLAUDE.md", "confidence": "EXTRACTED", "description": "Controls registry with NEP references"},
    {"id": "nep_300", "label": "NEP 300", "type": "standard", "source_file": "CLAUDE.md", "confidence": "EXTRACTED", "description": "Planification standard"},
    {"id": "nep_315", "label": "NEP 315", "type": "standard", "source_file": "CLAUDE.md", "confidence": "EXTRACTED", "description": "Connaissance de l entite standard"},
    {"id": "nep_320", "label": "NEP 320 / ISA 320", "type": "standard", "source_file": "CLAUDE.md", "confidence": "EXTRACTED", "description": "Seuil de signification standard"},
    {"id": "nep_330", "label": "NEP 330", "type": "standard", "source_file": "CLAUDE.md", "confidence": "EXTRACTED", "description": "Procedures d audit standard"},
    {"id": "nep_520", "label": "NEP 520", "type": "standard", "source_file": "CLAUDE.md", "confidence": "EXTRACTED", "description": "Procedures analytiques standard"},
    {"id": "risque", "label": "Risque audit", "type": "concept", "source_file": "CLAUDE.md", "confidence": "EXTRACTED", "description": "Audit risk identified during planning phase"},
    {"id": "assertions", "label": "Assertions audit", "type": "concept", "source_file": "CLAUDE.md", "confidence": "EXTRACTED", "description": "Audit assertions: existence, exhaustivite, evaluation, cut-off"},
    {"id": "seuil_signification", "label": "Seuil de signification", "type": "concept", "source_file": "CLAUDE.md", "confidence": "EXTRACTED", "description": "Materiality threshold calculated from financial aggregates"},
    {"id": "cartographie_risques", "label": "Cartographie des risques", "type": "concept", "source_file": "CLAUDE.md", "confidence": "EXTRACTED", "description": "Risk mapping table for the audit mission"},
    {"id": "programme_travail", "label": "Programme de travail", "type": "concept", "source_file": "CLAUDE.md", "confidence": "EXTRACTED", "description": "Work program auto-generated from validated risks"},
    {"id": "cycle_tresorerie", "label": "Cycle Tresorerie", "type": "concept", "source_file": "CLAUDE.md", "confidence": "EXTRACTED", "description": "Treasury cycle covering accounts 5xx"},
    {"id": "cycle_achats", "label": "Cycle Achats-Fournisseurs", "type": "concept", "source_file": "CLAUDE.md", "confidence": "EXTRACTED", "description": "Purchases cycle covering accounts 40x + 60x-62x"},
    {"id": "cycle_ventes", "label": "Cycle Ventes-Clients", "type": "concept", "source_file": "CLAUDE.md", "confidence": "EXTRACTED", "description": "Sales cycle covering accounts 41x + 70x-72x"},
    {"id": "page_dashboard", "label": "Dashboard Page", "type": "component", "source_file": "index.html", "confidence": "EXTRACTED", "description": "Mission list and creation page"},
    {"id": "page_planification", "label": "Planification Page", "type": "component", "source_file": "index.html", "confidence": "EXTRACTED", "description": "Planning page with 5 sections for risk analysis"},
    {"id": "page_controles", "label": "Controles Page", "type": "component", "source_file": "index.html", "confidence": "EXTRACTED", "description": "Audit controls execution page"},
    {"id": "page_cadrage", "label": "Cadrage Page", "type": "component", "source_file": "index.html", "confidence": "EXTRACTED", "description": "Mission parameters configuration page"},
    {"id": "donnee_sourcee", "label": "DonneeSourcee", "type": "concept", "source_file": "CLAUDE.md", "confidence": "EXTRACTED", "description": "Traceable data with projet_id, fichier_source_id, localisation"},
    {"id": "journal_audit", "label": "Journal audit", "type": "concept", "source_file": "CLAUDE.md", "confidence": "EXTRACTED", "description": "Audit trail logging all transitions, LLM calls, and human actions"},
    {"id": "sqlite_db", "label": "SQLite per-project DB", "type": "component", "source_file": "CLAUDE.md", "confidence": "EXTRACTED", "description": "Per-project database at ~/.probare/projets/{projet_id}/audit.db"},
    {"id": "fastapi_sidecar", "label": "FastAPI Sidecar", "type": "component", "source_file": "CLAUDE.md", "confidence": "EXTRACTED", "description": "Python backend sidecar for the Electron desktop app"},
    {"id": "electron_app", "label": "Electron App", "type": "component", "source_file": "index.html", "confidence": "EXTRACTED", "description": "Desktop application shell built with Electron"},
    {"id": "react_frontend", "label": "React Frontend", "type": "component", "source_file": "index.html", "confidence": "EXTRACTED", "description": "React + TypeScript + Tailwind UI layer"},
]

edges = [
    {"source": "cadrage", "target": "ingestion", "label": "transitions_to", "confidence": "EXTRACTED"},
    {"source": "ingestion", "target": "extraction", "label": "transitions_to", "confidence": "EXTRACTED"},
    {"source": "extraction", "target": "planification", "label": "transitions_to", "confidence": "EXTRACTED"},
    {"source": "planification", "target": "controles", "label": "transitions_to", "confidence": "EXTRACTED"},
    {"source": "controles", "target": "revue", "label": "transitions_to", "confidence": "EXTRACTED"},
    {"source": "revue", "target": "generation", "label": "transitions_to", "confidence": "EXTRACTED"},
    {"source": "generation", "target": "opinion", "label": "transitions_to", "confidence": "EXTRACTED"},
    {"source": "llm_philosophy", "target": "llm_client", "label": "enforced_by", "confidence": "EXTRACTED"},
    {"source": "llm_client", "target": "claude_sonnet", "label": "uses_by_default", "confidence": "EXTRACTED"},
    {"source": "llm_client", "target": "claude_haiku", "label": "uses_for_mapping", "confidence": "EXTRACTED"},
    {"source": "planification", "target": "seuil_signification", "label": "calculates", "confidence": "EXTRACTED"},
    {"source": "planification", "target": "cartographie_risques", "label": "produces", "confidence": "EXTRACTED"},
    {"source": "planification", "target": "programme_travail", "label": "generates", "confidence": "EXTRACTED"},
    {"source": "cartographie_risques", "target": "risque", "label": "contains", "confidence": "EXTRACTED"},
    {"source": "risque", "target": "assertions", "label": "relates_to", "confidence": "EXTRACTED"},
    {"source": "seuil_signification", "target": "nep_320", "label": "governed_by", "confidence": "EXTRACTED"},
    {"source": "planification", "target": "nep_300", "label": "governed_by", "confidence": "EXTRACTED"},
    {"source": "planification", "target": "nep_315", "label": "governed_by", "confidence": "EXTRACTED"},
    {"source": "controles", "target": "nep_330", "label": "governed_by", "confidence": "EXTRACTED"},
    {"source": "controles", "target": "cycle_tresorerie", "label": "covers", "confidence": "EXTRACTED"},
    {"source": "controles", "target": "cycle_achats", "label": "covers", "confidence": "EXTRACTED"},
    {"source": "controles", "target": "cycle_ventes", "label": "covers", "confidence": "EXTRACTED"},
    {"source": "controls_module", "target": "registry_py", "label": "declares_in", "confidence": "EXTRACTED"},
    {"source": "storage_module", "target": "sqlite_db", "label": "manages", "confidence": "EXTRACTED"},
    {"source": "statemachine_module", "target": "cadrage", "label": "manages_state", "confidence": "EXTRACTED"},
    {"source": "api_routes", "target": "fastapi_sidecar", "label": "part_of", "confidence": "EXTRACTED"},
    {"source": "fastapi_sidecar", "target": "planning_module", "label": "exposes", "confidence": "EXTRACTED"},
    {"source": "fastapi_sidecar", "target": "controls_module", "label": "exposes", "confidence": "EXTRACTED"},
    {"source": "fastapi_sidecar", "target": "storage_module", "label": "uses", "confidence": "EXTRACTED"},
    {"source": "electron_app", "target": "fastapi_sidecar", "label": "communicates_with", "confidence": "EXTRACTED"},
    {"source": "electron_app", "target": "react_frontend", "label": "hosts", "confidence": "EXTRACTED"},
    {"source": "react_frontend", "target": "page_dashboard", "label": "contains", "confidence": "EXTRACTED"},
    {"source": "react_frontend", "target": "page_planification", "label": "contains", "confidence": "EXTRACTED"},
    {"source": "react_frontend", "target": "page_controles", "label": "contains", "confidence": "EXTRACTED"},
    {"source": "react_frontend", "target": "page_cadrage", "label": "contains", "confidence": "EXTRACTED"},
    {"source": "donnee_sourcee", "target": "storage_module", "label": "stored_in", "confidence": "EXTRACTED"},
    {"source": "journal_audit", "target": "storage_module", "label": "written_to", "confidence": "EXTRACTED"},
    {"source": "llm_client", "target": "planification", "label": "interprets_for", "confidence": "EXTRACTED"},
    {"source": "llm_client", "target": "controles", "label": "interprets_exceptions_for", "confidence": "EXTRACTED"},
    {"source": "programme_travail", "target": "controles", "label": "drives", "confidence": "EXTRACTED"},
    {"source": "page_planification", "target": "planification", "label": "frontend_for", "confidence": "EXTRACTED"},
    {"source": "page_controles", "target": "controles", "label": "frontend_for", "confidence": "EXTRACTED"},
]

result = {
    "nodes": nodes,
    "edges": edges,
    "hyperedges": [
        {"nodes": ["cadrage", "ingestion", "extraction", "planification", "controles", "revue", "generation", "opinion"], "label": "audit_pipeline_sequence", "confidence": "EXTRACTED"},
        {"nodes": ["cycle_tresorerie", "cycle_achats", "cycle_ventes"], "label": "audit_cycles_covered", "confidence": "EXTRACTED"},
    ],
    "input_tokens": 0,
    "output_tokens": 0
}

out_path = Path("D:/projet/Audit_Comptable/graphify-out/.graphify_chunk_01.json")
out_path.parent.mkdir(parents=True, exist_ok=True)
out_path.write_text(json.dumps(result, indent=2, ensure_ascii=False), encoding="utf-8")
print("Wrote", len(nodes), "nodes and", len(edges), "edges to chunk file")
